name: test-vaultwarden-auto-confirm

volumes:
  vaultwarden-data:

services:
  app:
    image: vaultwarden/server:1.34.3
    restart: unless-stopped
    networks:
      default:
        aliases:
          - vaultwarden-container
    ports:
      - "8240:80"
    volumes:
      - type: volume
        source: vaultwarden-data
        target: /data
    environment:
      - TZ=Asia/Tokyo
      - DOMAIN=http://localhost:8240
      - INVITATIONS_ALLOWED=true
      - SIGNUPS_ALLOWED=true
      # ADMIN_TOKEN=admin-pass
      - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$usxm21N0w4LWKCXIbfB8MUW7nChwXu8oUAWcNcF/C1w$$r2xZQyHQLvHaI0NUFaJFgts4TkWlXMq5pv8OcIa1WmU
    healthcheck:
      test: curl -f -s http://localhost:80 || exit 1
      start_period: 300s
      start_interval: 3s
      timeout: 5s
      interval: 300s
      retries: 3

  confirmer:
    image: my/vaultwarden-auto-confirm
    pull_policy: never
    build:
      context: ../
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./assets/vwac
        target: /vwac
        read_only: true
        bind:
          create_host_path: false
    environment:
      - TZ=Asia/Tokyo
      - VWAC_SETTINGS_FILE=/vwac/settings.json
